import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    { type: 'autogenerated', dirName: 'authored' },
    {
      type: 'category',
      label: 'Decision Logs',
      link: { type: 'generated-index' },
      items: [
        { type: 'autogenerated', dirName: 'generated-docs/decision-logs' },
      ],
    },
  ] satisfies SidebarsConfig['string'],
};

export default sidebars;
